//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSL1GHT_IDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSL1GHT_IDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON0 {
            get {
                object obj = ResourceManager.GetObject("ICON0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;stdio.h&gt;
        ///#include &lt;string.h&gt;
        ///
        ///signed int main(signed int argc, const char* argv[])
        ///{
        ///	printf (&quot;Hello World!&quot;);
        ///	
        ///	return 0;
        ///}
        ///.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #---------------------------------------------------------------------------------
        ///# Clear the implicit built in rules
        ///#---------------------------------------------------------------------------------
        ///.SUFFIXES:
        ///#---------------------------------------------------------------------------------
        ///ifeq ($(strip $(PSL1GHT)),)
        ///$(error &quot;Please set PSL1GHT in your environment. export PSL1GHT=&lt;path&gt;&quot;)
        ///endif
        ///
        ///#---------------------------------------------------------------------------------
        ///#  TITLE, APPID [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string makefile {
            get {
                return ResourceManager.GetString("makefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 ::
        ///	Initial Commit
        ///
        ///.
        /// </summary>
        internal static string revisions {
            get {
                return ResourceManager.GetString("revisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;sfo&gt;
        ///	&lt;value name=&quot;APP_VER&quot; type=&quot;string&quot;&gt;
        ///		%VER%
        ///	&lt;/value&gt;
        ///	&lt;value name=&quot;ATTRIBUTE&quot; type=&quot;integer&quot;&gt;
        ///		133
        ///	&lt;/value&gt;
        ///	&lt;value name=&quot;BOOTABLE&quot; type=&quot;integer&quot;&gt;
        ///		1
        ///	&lt;/value&gt;
        ///	&lt;value name=&quot;CATEGORY&quot; type=&quot;string&quot;&gt;
        ///		HG
        ///	&lt;/value&gt;
        ///	&lt;value name=&quot;LICENSE&quot; type=&quot;string&quot;&gt;
        ///		%LICENSE%
        ///	&lt;/value&gt;
        ///	&lt;value name=&quot;PARENTAL_LEVEL&quot; type=&quot;integer&quot;&gt;
        ///		0
        ///	&lt;/value&gt;
        ///	&lt;value name=&quot;PS3_SYSTEM_VER&quot; type=&quot;string&quot;&gt;
        ///		03.4000
        ///	&lt;/value&gt;
        ///	&lt;value name=&quot;RESOLUTION&quot; type=&quot;integer&quot;&gt;
        ///		63
        ///	&lt;/va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfo {
            get {
                return ResourceManager.GetString("sfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_class {
            get {
                object obj = ResourceManager.GetObject("tree_class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_file {
            get {
                object obj = ResourceManager.GetObject("tree_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_folder {
            get {
                object obj = ResourceManager.GetObject("tree_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tree_header {
            get {
                object obj = ResourceManager.GetObject("tree_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
